Update Cake Auth Actions
codekanzlei/cake-auth-actions pull request #5
Opened 2017-11-06 12:44 UTC by jonathan-neugber

TODO:
- [ ] Move UserRights outside of AuthActionsTrait
- [x] Fix auth library
- [ ] Improve doc blocks
- [ ] Migrate away from cookiecomponent
- [x] update readme

2017-11-09 10:15 UTC, cleptric requested changes

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +     * 		'controller' => array(
Indentation is off

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +     * @var string
That's wrong

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +     * @param array $options Additional options
array|null

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +    public function isAuthorized($user, $plugin, $controller, $action) {
Are we going to add all typehints? If not, at least `array` is missing.

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +            $isAuthorized = true;
We could return early at this stage

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +        }
Missing blank line before return

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +        if (in_array($user['role'], $permissions)) {
We could add this to the `if` above

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +                return true;
That indentation looks odd

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +            $controller = Inflector::underscore($controller);
Do this first and drop the else condition.

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +        $key = ($plugin ? $plugin . '.' : '') . $controller;
There are methods for this inside the Cake Core.

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +                $isPublic = true;
return true

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +                $isPublic = true;
return true

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +                $isPublic = true;
return true

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +        return $isPublic;
return false

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +    public function urlAllowed($user, $url) {
type hints

2017-11-09 10:15 UTC, cleptric commented on src/Lib/AuthActions.php
> +        return $this->isAuthorized($user, $route['plugin'], $route['controller'], $route['action']);
Black line. No method calls as return.

2017-11-09 10:15 UTC, cleptric commented on src/Lib/UserRights.php
> +            return AuthActions::isUserAuthorized($user, $this->_rightsConfig, $right);
Indentation

2017-11-13 18:49 UTC, felixkempf commented on README.md
> +					    'AND' => [
Why not doing it the same way as cake in the query conditions:
Elements in an array are linked by AND unless stated otherwise.

2017-11-13 18:54 UTC, felixkempf commented on src/Lib/Auth.php
> +        }
The two ifs above can be simplified to:
```
if (!array_key_exists($permission, $config)) {
   return in_array($permission, $config);
}
```

2017-11-13 19:00 UTC, felixkempf commented on src/Lib/AutoLoginTrait.php
> +            if (Configure::load('auto_login') === false) {
`if (!$salt && Configure::load('auto_login') === false) {`

2017-11-13 19:01 UTC, felixkempf commented on src/Lib/UserRights.php
> +    public function __construct(array $rightsConfig = [])
Return type in DocBlock and signature missing

2017-11-16 10:57 UTC, cleptric requested changes

2017-11-16 10:57 UTC, cleptric commented on src/Controller/Component/AuthUtilsComponent.php
> +    public function addRememberMeCookie(string $userId, array $options = []): void
The `string` type hint breaks application with `integer` user ids

2019-11-05 13:24 UTC, closed without merging

2019-11-05 13:24 UTC, cleptric commented
Done in https://github.com/scherersoftware/cake-auth-actions/pull/6